config/routes.rb
Rails.application.routes.draw do
 root 'subs#index'

 resources :subs do
  resources :topics
end

  scope 'topics/:topic_id', as: 'topic' do
    resources :comments, only: [:new, :create]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  before_save :check_author
  validates :body, presence: true

  def check_author
    if self.author.blank? 
      self.author = 'Anon Coward'
    end
  end
end

app/models/sub.rb
class Sub < ApplicationRecord
  has_many :topics, dependent: :destroy
  validates :name, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :sub
  has_many :comments, dependent: :destroy
  validates :name, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :verify_paid

  def verify_paid
    @paid = true
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_topic


  def new
    @comment = Comment.new
  end

  def create
    @comment = @topic.comments.new(comment_params)
    if @comment.save
      redirect_to sub_topic_path(@topic.sub_id, @topic)
    else
      render :new
    end
  end

  private
    def set_topic
      @topic = Topic.find(params[:topic_id])
    end


    def comment_params
      params.require(:comment).permit(:body, :author)
    end


end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  skip_before_action :verify_paid, only: [:index, :show]
  before_action :set_sub, only: [:show, :update, :edit, :destroy]
  

  def index
    @subs = Sub.all
  end

  def show
  end

  def new
    @sub = Sub.new
    render :form
  end

  def edit
    render :form
  end

  def create
    @sub = Sub.new(sub_params)

    if @sub.save
      redirect_to @sub
    else
      render :from
    end
  end


  def update
    if @sub.update(sub_params)
      redirect_to @sub
    else
      render :form
    end
  end

  def destroy
    @sub.destroy
    redirect_to subs_path
  end


  private

    def set_sub
      @sub = Sub.find(params[:id])
    end
    
    def sub_params
      params.require(:sub).permit(:name)
    end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_sub
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = @sub.topics
  end

  def show
  end

  def new
    @topic = Topic.new
    render :form
  end

  def edit
    render :form
  end

  def create
    @topic = @sub.topics.create(topic_params)
      if @topic.save
        ## redirect_to [@sub, @topic]
        redirect_to sub_topic_path(@sub, @topic)
      else
        render :form
      end
  end

  def update
    if @topic.update(topic_params)
      redirect_to sub_topic_path(@sub, @topic)
    else
      render :form
    end
  end

  def destroy
    @topic.destroy
    redirect_to sub_topics_path(@sub)
  end

  private

    def set_sub
      @sub = Sub.find(params[:sub_id])
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:name, :body)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sub_helper.rb
module SubHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_comment.html.erb
<hr />
<p> Author: <%= comment.author %> </p>
<p> <strong> <%= comment.body %> </strong> </p>
<hr />

app/views/comments/new.html.erb
<h1> Add A Comment </h1>

<%= form_for [@topic, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author, placeholder: 'Leave blank for anon' %>
  <br />
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/form.html.erb
<h1><%= @sub.id ? 'Edit Sub' : 'Create Sub' %></h1>
<hr ?>

<%= form_for @sub do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.submit %> <!-- f.submit, nameonbutton, html -->

<% end %>

app/views/subs/index.html.erb
<h1> Click To View Sub </h1>
<%= link_to "Create New Sub", new_sub_path %>

<ul>
  <% @subs.each do |sub| %>
    <li>
      <%= link_to sub.name, sub %> <!-- sub is equal to sub_path(sub.id) -->
    </li>
  <% end %>
</ul>

app/views/subs/show.html.erb
<h1> <%= @sub.name %> </h1>
<hr />
<p> What would you like to do? </p>

<%= link_to 'View Topics', sub_topics_path(@sub) %>
<br />
<%= link_to 'Edit Sub', edit_sub_path(@sub) %>
<%= link_to 'Delete Sub', @sub, method: :delete %>
<%= link_to 'Back', subs_path %>

app/views/topics/form.html.erb
<h1> <%= @topic.id ? 'Edit Topic' : 'Create Topic' %> </h1>
<hr />
<%= form_for [@sub, @topic] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.submit %>  
<% end %>

app/views/topics/index.html.erb
<h1><%= @sub.name %> Topics </h1>
<%= link_to 'Create New Topic', new_sub_topic_path(@sub) %>
<ul>
  <% @topics.each do |topic| %>
    <li>
      <%= link_to topic.name, sub_topic_path(@sub, topic) %>
    </li>
  <% end %>
</ul>
 <%= link_to 'Back to Subs', subs_path %>

app/views/topics/show.html.erb
<h1> <%= @sub.name %> - <%= @topic.name %> </h1>
<p> <%= @topic.body %> </p>
<h2> Comments </h2>

<% @topic.comments.each do |comment| %>
  <%= render 'comments/comment', { comment: comment } %>
<% end %>

<hr />

<%= link_to 'Edit Topic', edit_sub_topic_path(@sub, @topic) %>
<%= link_to 'Delete Topic', [@sub, @topic], method: :delete %>
<%= link_to 'Back', sub_topics_path(@sub) %>
<%= link_to 'Add Comment', new_topic_comment_path(@topic) %>